<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products= [
            'FOOTWEAR' => [
              0 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '40',
                'COLOR' => 'BROWN',
                'PRICE' => '350.00',
              ],
              1 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '44',
                'COLOR' => 'BROWN',
                'PRICE' => '350.00',
              ],
              2 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '42',
                'COLOR' => 'BROWN',
                'PRICE' => '350.00',
              ],
              3 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '41',
                'COLOR' => 'BROWN',
                'PRICE' => '350.00',
              ],
              4 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '44',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '350.00',
              ],
              5 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '42',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '350.00',
              ],
              6 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '42',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '350.00',
              ],
              7 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '41',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '350.00',
              ],
              8 => [
                'BRAND' => 'GENIO',
                'SIZE' => '42',
                'COLOR' => 'BLACK',
                'PRICE' => '500.00',
              ],
              9 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '44',
                'COLOR' => 'BLUE',
                'PRICE' => '350.00',
              ],
              10 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '40',
                'COLOR' => 'BLUE',
                'PRICE' => '350.00',
              ],
              11 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '41',
                'COLOR' => 'BLUE',
                'PRICE' => '350.00',
              ],
              12 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '42',
                'COLOR' => 'BLUE',
                'PRICE' => '350.00',
              ],
              13 => [
                'BRAND' => 'GENIO',
                'SIZE' => '47',
                'COLOR' => 'BLACK',
                'PRICE' => '500.00',
              ],
              14 => [
                'BRAND' => 'GENIO',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '600.00',
              ],
              15 => [
                'BRAND' => 'GENIO',
                'SIZE' => '40',
                'COLOR' => 'BLACK',
                'PRICE' => '300.00',
              ],
              16 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '43',
                'COLOR' => 'BLACK',
                'PRICE' => '450.00',
              ],
              17 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '42',
                'COLOR' => 'BLACK',
                'PRICE' => '450.00',
              ],
              18 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '41',
                'COLOR' => 'BLACK',
                'PRICE' => '450.00',
              ],
              19 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '44',
                'COLOR' => 'BLACK',
                'PRICE' => '450.00',
              ],
              20 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '450.00',
              ],
              21 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '41',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '450.00',
              ],
              22 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '42',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '450.00',
              ],
              23 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '44',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '450.00',
              ],
              24 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '45',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '450.00',
              ],
              25 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '40',
                'COLOR' => 'BLACK',
                'PRICE' => '350.00',
              ],
              26 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '44',
                'COLOR' => 'BLACK',
                'PRICE' => '350.00',
              ],
              27 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '40',
                'COLOR' => 'MIRROR BLACK',
                'PRICE' => '350.00',
              ],
              28 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '40',
                'COLOR' => 'BLACK',
                'PRICE' => '350.00',
              ],
              29 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '41',
                'COLOR' => 'BLACK',
                'PRICE' => '350.00',
              ],
              30 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '42',
                'COLOR' => 'BLACK',
                'PRICE' => '350.00',
              ],
              31 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '44',
                'COLOR' => 'BLACK',
                'PRICE' => '350.00',
              ],
              32 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '550.00',
              ],
              33 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '45',
                'COLOR' => 'BLACK',
                'PRICE' => '550.00',
              ],
              34 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '41',
                'COLOR' => 'BLACK',
                'PRICE' => '550.00',
              ],
              35 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '42',
                'COLOR' => 'BLACK',
                'PRICE' => '550.00',
              ],
              36 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '43',
                'COLOR' => 'BLACK',
                'PRICE' => '550.00',
              ],
              37 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '44',
                'COLOR' => 'BLACK',
                'PRICE' => '550.00',
              ],
              38 => [
                'BRAND' => 'MONTONE',
                'SIZE' => '46',
                'COLOR' => 'BROWN',
                'PRICE' => '550.00',
              ],
              39 => [
                'BRAND' => 'ROVIGO',
                'SIZE' => '44',
                'COLOR' => 'BROWN',
                'PRICE' => '280.00',
              ],
              40 => [
                'BRAND' => 'ROVIGO',
                'SIZE' => '43',
                'COLOR' => 'BROWN',
                'PRICE' => '280.00',
              ],
              41 => [
                'BRAND' => 'ROVIGO',
                'SIZE' => '41',
                'COLOR' => 'BROWN',
                'PRICE' => '280.00',
              ],
              42 => [
                'BRAND' => 'ROVIGO',
                'SIZE' => '43',
                'COLOR' => 'BLUE',
                'PRICE' => '280.00',
              ],
              43 => [
                'BRAND' => 'X RAY',
                'SIZE' => '46',
                'COLOR' => 'BROWN',
                'PRICE' => '200.00',
              ],
              44 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '44',
                'COLOR' => 'WINE',
              ],
              45 => [
                'BRAND' => 'ROVIGO PLUS',
                'SIZE' => '44',
                'COLOR' => 'WINE',
                'PRICE' => '300.00',
              ],
              46 => [
                'BRAND' => 'ROVIGO',
                'SIZE' => '43',
                'COLOR' => 'BLACK',
                'PRICE' => '280.00',
              ],
              47 => [
                'BRAND' => 'GENIO',
                'SIZE' => '46',
                'COLOR' => 'BROWN',
                'PRICE' => '650.00',
              ],
              48 => [
                'BRAND' => 'ROVIGO',
                'SIZE' => '41',
                'COLOR' => 'BLACK',
                'PRICE' => '200.00',
                'DESCRIPTION' => 'SLIPPERS',
              ],
              49 => [
                'BRAND' => 'ROVIGO',
                'SIZE' => '40',
                'PRICE' => '200.00',
                'DESCRIPTION' => 'SLIPPERS',
              ],
              50 => [
                'BRAND' => 'ROVIGO',
                'SIZE' => '43',
                'COLOR' => 'BLACK',
                'PRICE' => '200.00',
                'DESCRIPTION' => 'SLIPPERS',
              ],
              51 => [
                'BRAND' => 'ROVIGO',
                'SIZE' => '43',
                'COLOR' => 'WINE',
                'PRICE' => '200.00',
                'DESCRIPTION' => 'SLIPPERS',
              ],
              52 => [
                'BRAND' => 'ROVIGO',
                'SIZE' => '40',
                'COLOR' => 'BROWN',
                'PRICE' => '200.00',
                'DESCRIPTION' => 'SLIPPERS',
              ],
              53 => [
                'BRAND' => 'FERRAGAMO',
                'SIZE' => '43',
                'COLOR' => 'BROWN',
                'PRICE' => '250.00',
                'DESCRIPTION' => 'SLIPPERS',
              ],
            ],
            'SUITS' => [
              0 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '500',
                'CODE' => '00905322113305',
              ],
              1 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'BLACK',
                'PRICE' => '500',
                'CODE' => '00905322113305',
              ],
              2 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'BLACK',
                'PRICE' => '500',
                'CODE' => '00905322113305',
              ],
              3 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'GRAY',
                'PRICE' => '500',
                'CODE' => '00905322113305',
              ],
              4 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'GRAY',
                'PRICE' => '500',
                'CODE' => '00905322113305',
              ],
              5 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'GRAY',
                'PRICE' => '500',
                'CODE' => '00905322113305',
              ],
              6 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'BLUE',
                'PRICE' => '500',
                'CODE' => '309007156009',
              ],
              7 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'BLUE',
                'PRICE' => '500',
                'CODE' => '309007156009',
              ],
              8 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'BLUE',
                'PRICE' => '500',
                'CODE' => '309007156009',
              ],
              9 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'BLUE',
                'PRICE' => '500',
                'CODE' => '309007156009',
              ],
              10 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'BLUE',
                'PRICE' => '500',
                'CODE' => '309007156009',
              ],
              11 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'BLUE',
                'PRICE' => '500',
                'CODE' => '309007156009',
              ],
              12 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              13 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              14 => [
                'BRAND' => 'PAULO BOSELLI',
                'SIZE' => '46',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '600',
                'CODE' => '1234567890128',
              ],
              15 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BROWN',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              16 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'GRAY',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              17 => [
                'BRAND' => 'PACO ROMANO',
                'SIZE' => '46',
                'COLOR' => 'CHECKED WINE',
                'PRICE' => '700',
                'CODE' => '1234567890128',
              ],
              18 => [
                'BRAND' => 'DANIEL BROWN',
                'SIZE' => '46',
                'COLOR' => 'CHECKED GRAY',
                'PRICE' => '250',
                'CODE' => '+123456789246',
                'DESCRIPTION' => 'BLAZZER',
              ],
              19 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              20 => [
                'BRAND' => 'DANIEL BROWN',
                'SIZE' => '46',
                'COLOR' => 'CHECKED BLUE',
                'PRICE' => '600',
                'CODE' => '+123456789246',
                'DESCRIPTION' => 'BLAZZER',
              ],
              21 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLUE',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              22 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              23 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              24 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              25 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLUE',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              26 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              27 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLUE ',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              28 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              29 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '44',
                'COLOR' => 'BLUE',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              30 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLUE',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              31 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              32 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '46',
                'COLOR' => 'STRIPPLE',
                'PRICE' => '700',
                'CODE' => '8681500000015',
              ],
              33 => [
                'BRAND' => 'PAULO BOSELLI',
                'SIZE' => '46',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '600',
                'CODE' => '1234567890128',
              ],
              34 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              35 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '46',
                'COLOR' => 'STRIPPED BLACK',
                'PRICE' => '700',
                'CODE' => '8681500000015',
              ],
              36 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              37 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'DARK GARY',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              38 => [
                'BRAND' => 'PACO ROMANO',
                'SIZE' => '46',
                'COLOR' => 'CHECKED GRAY',
                'PRICE' => '700',
                'CODE' => '1234567890128',
              ],
              39 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'NAVY BLUE',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              40 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'NAVY BLUE',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              41 => [
                'BRAND' => 'MARIN BROWN',
                'SIZE' => '46',
                'COLOR' => 'NAVY BLUE',
                'PRICE' => '600',
                'CODE' => '12345678901286',
              ],
              42 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'NAVY BLUE',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              43 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLUE',
                'PRICE' => '600',
                'CODE' => '309007156009',
              ],
              44 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '46',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              45 => [
                'BRAND' => 'CASILA',
                'SIZE' => '50',
                'COLOR' => 'BLACK',
                'PRICE' => '700',
                'CODE' => '603500',
              ],
              46 => [
                'BRAND' => 'PACO ROMANO',
                'SIZE' => '50',
                'COLOR' => 'ASH',
                'PRICE' => '600',
                'CODE' => '1234567890128',
              ],
              47 => [
                'BRAND' => 'PAULO BOSELLI',
                'SIZE' => '50',
                'PRICE' => '600',
                'CODE' => '1234567890128',
              ],
              48 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '50',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              49 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '50',
                'COLOR' => 'STRIPPED BLUE',
                'PRICE' => '600',
                'CODE' => '8681500000015',
              ],
              50 => [
                'BRAND' => 'DANIEL BROWN',
                'SIZE' => '50',
                'COLOR' => 'CHECKED GRAY',
                'PRICE' => '250',
                'CODE' => '+123456789246',
                'DESCRIPTION' => 'BLAZZER',
              ],
              51 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '50',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              52 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '50',
                'COLOR' => 'CHECKED BLACK',
                'PRICE' => '600',
                'CODE' => '8681500000015',
              ],
              53 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '50',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              54 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '54',
                'COLOR' => 'STRIPPED BLACK',
                'PRICE' => '700',
                'CODE' => '8681500000015',
              ],
              55 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '52',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              56 => [
                'BRAND' => 'PAULO BOSELLI',
                'SIZE' => '54',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '1234567890128',
              ],
              57 => [
                'BRAND' => 'CASILA',
                'SIZE' => '54',
                'COLOR' => 'BLACK',
                'PRICE' => '700',
                'CODE' => '603500',
              ],
              58 => [
                'BRAND' => 'ELINO',
                'SIZE' => '54',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '+123456789246',
              ],
              59 => [
                'BRAND' => 'DOMENICO VACCA',
                'SIZE' => '54',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '+905321311114',
              ],
              60 => [
                'BRAND' => 'PAULO BOSELLI',
                'SIZE' => '54',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '600',
                'CODE' => '1234567890128',
              ],
              61 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '54',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              62 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '54',
                'COLOR' => 'DARK BROWN',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              63 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '54',
                'COLOR' => 'NAVY BLUE',
                'PRICE' => '600',
                'CODE' => '+123456789246',
              ],
              64 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '54',
                'COLOR' => 'STRIPPED BLUE',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              65 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '54',
                'COLOR' => 'STRIPPED BLACK',
                'PRICE' => '600',
                'CODE' => '8681500000015',
              ],
              66 => [
                'BRAND' => 'MARIN BROWN',
                'SIZE' => '54',
                'COLOR' => 'NAVY BLUE',
                'PRICE' => '600',
                'CODE' => '12345678901286',
              ],
              67 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '54',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              68 => [
                'BRAND' => 'DIENZO BROWN',
                'SIZE' => '54',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '700',
                'CODE' => '8925132464',
              ],
              69 => [
                'BRAND' => 'DANIEL BROWN',
                'SIZE' => '56',
                'COLOR' => 'CHECKED BLUE',
                'PRICE' => '250',
                'CODE' => '+123456789246',
                'DESCRIPTION' => 'BLAZZER',
              ],
              70 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '56',
                'COLOR' => 'BLUE',
                'PRICE' => '600',
                'CODE' => '+123456789246',
              ],
              71 => [
                'BRAND' => 'DOMENICO VACCA',
                'SIZE' => '56',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '+905321311114',
              ],
              72 => [
                'BRAND' => 'GIOLETTI',
                'SIZE' => '56',
                'COLOR' => 'BLACK',
                'PRICE' => '700',
                'CODE' => '+905321311114',
              ],
              73 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '56',
                'COLOR' => 'BLACK',
                'PRICE' => '700',
                'CODE' => '0000007857',
              ],
              74 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '56',
                'COLOR' => 'STRIPPED BLUE',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              75 => [
                'BRAND' => 'PACO ROMANO',
                'SIZE' => '56',
                'COLOR' => 'CHECKED ASH',
                'PRICE' => '700',
                'CODE' => '1234567890128',
              ],
              76 => [
                'BRAND' => 'PACO ROMANO',
                'SIZE' => '56',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '600',
                'CODE' => '1234567890128',
              ],
              77 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '56',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              78 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '56',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              79 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '56',
                'COLOR' => 'NAVY BLUE',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              80 => [
                'BRAND' => 'DIENZO BROWN',
                'SIZE' => '56',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '700',
                'CODE' => '8925132464',
              ],
              81 => [
                'BRAND' => 'PAULO BOSELLI',
                'SIZE' => '56',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '600',
                'CODE' => '1234567890128',
              ],
              82 => [
                'BRAND' => 'OTTIMA',
                'SIZE' => '56',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '00905322113305',
              ],
              83 => [
                'BRAND' => 'CULTUS',
                'SIZE' => '56',
                'COLOR' => 'BLUE',
                'PRICE' => '700',
                'CODE' => '8925132464',
              ],
              84 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '56',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '600',
                'CODE' => '1234567890128',
              ],
              85 => [
                'BRAND' => 'DOMENICO VACCA',
                'SIZE' => '64',
                'COLOR' => 'BLACK',
                'PRICE' => '600',
                'CODE' => '05321311114',
              ],
              86 => [
                'BRAND' => 'SU MISURA',
                'SIZE' => '64',
                'COLOR' => 'ASH',
                'PRICE' => '600',
                'CODE' => '05321311114',
              ],
              87 => [
                'BRAND' => 'SU MISURA',
                'SIZE' => '62',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '700',
                'CODE' => '05321311114',
              ],
              88 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '62',
                'COLOR' => 'CHECKED ORANGE',
                'PRICE' => '250',
                'CODE' => '+123456789246',
                'DESCRIPTION' => 'BLAZZER',
              ],
              89 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '60',
                'COLOR' => 'CHECKED GREEN',
                'PRICE' => '250',
                'CODE' => '+123456789246',
                'DESCRIPTION' => 'BLAZZER',
              ],
              90 => [
                'BRAND' => 'ZIGGLER',
                'SIZE' => '60',
                'COLOR' => 'CHECKED ORANGE',
                'PRICE' => '250',
                'CODE' => '+123456789246',
                'DESCRIPTION' => 'BLAZZER',
              ],
              91 => [
                'BRAND' => 'DIENZO BROWN',
                'SIZE' => '60',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '700',
                'CODE' => '+123456789246',
              ],
              92 => [
                'BRAND' => 'SU MISURA',
                'SIZE' => '60',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '700',
                'CODE' => '6M60025',
              ],
            ],
            'TROUSERS' => [
              0 => [
                'BRAND' => 'ENJOY JEANS',
                'SIZE' => '31',
                'COLOR' => 'FADED BLUE',
                'CODE' => '2612',
              ],
              1 => [
                'BRAND' => 'ENJOY JEANS',
                'SIZE' => '32',
                'COLOR' => 'FADED BLUE',
                'CODE' => '2612',
              ],
              2 => [
                'BRAND' => 'ENJOY JEANS',
                'SIZE' => '30',
                'COLOR' => 'FADED BLUE',
                'CODE' => '2612',
              ],
              3 => [
                'BRAND' => 'ENJOY JEANS',
                'SIZE' => '36',
                'COLOR' => 'FADED BLUE',
                'CODE' => '2612',
              ],
              4 => [
                'BRAND' => 'ENJOY JEANS',
                'SIZE' => '34',
                'COLOR' => 'FADED BLUE',
                'CODE' => '2612',
              ],
              5 => [
                'BRAND' => 'ENJOY JEANS',
                'SIZE' => '38',
                'COLOR' => 'FADED BLUE',
                'CODE' => '2612',
              ],
              6 => [
                'BRAND' => 'ENJOY JEANS',
                'SIZE' => '33',
                'COLOR' => 'FADED BLUE',
                'CODE' => '2612',
              ],
              7 => [
                'BRAND' => 'ENJOY JEANS',
                'SIZE' => '32',
                'COLOR' => 'FADED BLUE',
                'CODE' => '2612',
              ],
              8 => [
                'BRAND' => 'DSQUARED 2',
                'SIZE' => '30',
                'COLOR' => 'BLUE',
                'CODE' => '2890',
              ],
              9 => [
                'BRAND' => 'DSQUARED 3',
                'SIZE' => '31',
                'COLOR' => 'BLUE',
                'CODE' => '2890',
              ],
              10 => [
                'BRAND' => 'DSQUARED 4',
                'SIZE' => '32',
                'COLOR' => 'BLUE',
                'CODE' => '2890',
              ],
              11 => [
                'BRAND' => 'DSQUARED 5',
                'SIZE' => '33',
                'COLOR' => 'BLUE',
                'CODE' => '2890',
              ],
              12 => [
                'BRAND' => 'DSQUARED 6',
                'SIZE' => '34',
                'COLOR' => 'BLUE',
                'CODE' => '2890',
              ],
              13 => [
                'BRAND' => 'DSQUARED 7',
                'SIZE' => '32',
                'COLOR' => 'BLUE',
              ],
              14 => [
                'BRAND' => 'DR ICON',
                'SIZE' => '32',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2899',
              ],
              15 => [
                'BRAND' => 'DR ICON',
                'SIZE' => '34',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2899',
              ],
              16 => [
                'BRAND' => 'DR ICON',
                'SIZE' => '38',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2899',
              ],
              17 => [
                'BRAND' => 'DR ICON',
                'SIZE' => '32',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2899',
              ],
              18 => [
                'BRAND' => 'DR ICON',
                'SIZE' => '31',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2899',
              ],
              19 => [
                'BRAND' => 'DR ICON',
                'SIZE' => '33',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2899',
              ],
              20 => [
                'BRAND' => 'DR ICON',
                'SIZE' => '30',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2899',
              ],
              21 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              22 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              23 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              24 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              25 => [
                'BRAND' => 'LTC',
                'SIZE' => '34',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              26 => [
                'BRAND' => 'LTC',
                'SIZE' => '33',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              27 => [
                'BRAND' => 'LTC',
                'SIZE' => '32',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              28 => [
                'BRAND' => 'LTC',
                'SIZE' => '36',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              29 => [
                'BRAND' => 'LTC',
                'SIZE' => '36',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              30 => [
                'BRAND' => 'LTC',
                'SIZE' => '36',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              31 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '42',
                'COLOR' => 'COFFEE',
                'CODE' => '20163006',
              ],
              32 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '42',
                'COLOR' => 'COFFEE',
                'CODE' => '20163006',
              ],
              33 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '46',
                'COLOR' => 'COFFEE',
                'CODE' => '20163006',
              ],
              34 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '52',
                'COLOR' => 'COFFEE',
                'CODE' => '20163006',
              ],
              35 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '48',
                'COLOR' => 'COFFEE',
                'CODE' => '20163006',
              ],
              36 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '50',
                'COLOR' => 'COFFEE',
                'CODE' => '20163006',
              ],
              37 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '48',
                'COLOR' => 'COFFEE',
                'CODE' => '20163006',
              ],
              38 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '48',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              39 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '48',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              40 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '42',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              41 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '44',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              42 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '42',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              43 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '48',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              44 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              45 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              46 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              47 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              48 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              49 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '52',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              50 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '50',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              51 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '52',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              52 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => '20163006',
              ],
              53 => [
                'BRAND' => 'JM MARTIN',
                'SIZE' => '34',
                'COLOR' => 'DEEP ORANGE',
                'PRICE' => '150',
                'CODE' => '601971',
              ],
              54 => [
                'BRAND' => 'JM MARTIN',
                'SIZE' => '44',
                'COLOR' => 'DEEP ORANGE',
                'PRICE' => '150',
                'CODE' => '601971',
              ],
              55 => [
                'BRAND' => 'JM MARTIN',
                'SIZE' => '40',
                'COLOR' => 'DEEP ORANGE',
                'PRICE' => '150',
                'CODE' => '601971',
              ],
              56 => [
                'BRAND' => 'JM MARTIN',
                'SIZE' => '42',
                'COLOR' => 'DEEP ORANGE',
                'PRICE' => '150',
                'CODE' => '601971',
              ],
              57 => [
                'BRAND' => 'JM MARTIN',
                'SIZE' => '48',
                'COLOR' => 'DEEP ORANGE',
                'PRICE' => '150',
                'CODE' => '601971',
              ],
              58 => [
                'BRAND' => 'PIERRE CARLOS',
                'SIZE' => '50',
                'COLOR' => 'WINE',
                'CODE' => '554691236763',
              ],
              59 => [
                'BRAND' => 'PIERRE CARLOS',
                'SIZE' => '52',
                'COLOR' => 'WINE',
              ],
              60 => [
                'BRAND' => 'LTC',
                'SIZE' => '32',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              61 => [
                'BRAND' => 'LTC',
                'SIZE' => '33',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              62 => [
                'BRAND' => 'LTC',
                'SIZE' => '34',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              63 => [
                'BRAND' => 'LTC',
                'SIZE' => '36',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              64 => [
                'BRAND' => 'LTC',
                'SIZE' => '38',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              65 => [
                'BRAND' => 'LTC',
                'SIZE' => '40',
                'COLOR' => 'BLUE',
                'CODE' => '4688B',
              ],
              66 => [
                'BRAND' => 'MONAR',
                'SIZE' => '48',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              67 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              68 => [
                'BRAND' => 'MONAR',
                'SIZE' => '44',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              69 => [
                'BRAND' => 'MONAR',
                'SIZE' => '52',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              70 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '50',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '20163006',
              ],
              71 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '40',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '20163006',
              ],
              72 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '48',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '20163006',
              ],
              73 => [
                'BRAND' => 'GIORGIO ARMANI',
                'SIZE' => '40',
                'COLOR' => 'BLACK',
                'CODE' => '2002094',
              ],
              74 => [
                'BRAND' => 'LION PARK',
                'SIZE' => '38',
                'COLOR' => 'BLACK',
                'CODE' => '2002094',
              ],
              75 => [
                'BRAND' => 'LION PARK',
                'SIZE' => '38',
                'COLOR' => 'BLACK',
              ],
              76 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => '2002094',
              ],
              77 => [
                'BRAND' => 'MONAR',
                'SIZE' => '44',
                'COLOR' => 'DARK BROWN',
                'CODE' => 'W3505',
              ],
              78 => [
                'BRAND' => 'MONAR',
                'SIZE' => '54',
                'COLOR' => 'DARK BROWN',
                'CODE' => 'W3505',
              ],
              79 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'DARK BROWN',
                'CODE' => 'W3505',
              ],
              80 => [
                'BRAND' => 'MONAR',
                'SIZE' => '42',
                'COLOR' => 'DARK BROWN',
                'CODE' => 'W3505',
              ],
              81 => [
                'BRAND' => 'MONAR',
                'SIZE' => '44',
                'COLOR' => 'DARK BROWN',
                'CODE' => 'W3505',
              ],
              82 => [
                'BRAND' => 'XLEON',
                'SIZE' => '34',
                'COLOR' => 'DARK BROWN',
                'CODE' => '2131',
              ],
              83 => [
                'BRAND' => 'XLEON',
                'SIZE' => '30',
                'COLOR' => 'DARK BROWN',
                'CODE' => '2131',
              ],
              84 => [
                'BRAND' => 'XLEON',
                'SIZE' => '31',
                'COLOR' => 'DARK BROWN',
                'CODE' => '2131',
              ],
              85 => [
                'BRAND' => 'XLEON',
                'SIZE' => '32',
                'COLOR' => 'DARK BROWN',
                'CODE' => '2131',
              ],
              86 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'DARK BROWN',
                'CODE' => '2131',
              ],
              87 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'DARK BROWN',
                'CODE' => '2131',
              ],
              88 => [
                'BRAND' => 'XLEON',
                'SIZE' => '38',
                'COLOR' => 'DARK BROWN',
                'CODE' => '2131',
              ],
              89 => [
                'BRAND' => 'XLEON',
                'SIZE' => '40',
                'COLOR' => 'DARK BROWN',
                'CODE' => '2131',
              ],
              90 => [
                'BRAND' => 'XLEON',
                'SIZE' => '34',
                'COLOR' => 'BROWN',
                'CODE' => 'B-2043',
              ],
              91 => [
                'BRAND' => 'XLEON',
                'SIZE' => '40',
                'COLOR' => 'BROWN',
                'CODE' => 'B-2043',
              ],
              92 => [
                'BRAND' => 'XLEON',
                'SIZE' => '31',
                'COLOR' => 'BROWN',
                'CODE' => 'B-2043',
              ],
              93 => [
                'BRAND' => 'XLEON',
                'SIZE' => '32',
                'COLOR' => 'BROWN',
                'CODE' => 'B-2043',
              ],
              94 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'BROWN',
                'CODE' => 'B-2043',
              ],
              95 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'BROWN',
                'CODE' => 'B-2043',
              ],
              96 => [
                'BRAND' => 'XLEON',
                'SIZE' => '34',
                'COLOR' => 'BROWN',
                'CODE' => 'B-2043',
              ],
              97 => [
                'BRAND' => 'XLEON',
                'SIZE' => '36',
                'COLOR' => 'BROWN',
                'CODE' => 'B-2043',
              ],
              98 => [
                'BRAND' => 'XLEON',
                'SIZE' => '38',
                'COLOR' => 'BROWN',
                'CODE' => 'B-2043',
              ],
              99 => [
                'BRAND' => 'XLEON',
                'SIZE' => '38',
                'COLOR' => 'BROWN',
                'CODE' => 'B-2043',
              ],
              100 => [
                'BRAND' => 'LTC',
                'SIZE' => '32',
                'COLOR' => 'BLACK',
                'CODE' => '4688B',
              ],
              101 => [
                'BRAND' => 'LTC',
                'SIZE' => '36',
                'COLOR' => 'BLACK',
                'CODE' => '4688B',
              ],
              102 => [
                'BRAND' => 'LTC',
                'SIZE' => '38',
                'COLOR' => 'BLACK',
                'CODE' => '4688B',
              ],
              103 => [
                'BRAND' => 'LTC',
                'SIZE' => '40',
                'COLOR' => 'BLACK',
                'CODE' => '4688B',
              ],
              104 => [
                'BRAND' => 'LTC',
                'SIZE' => '34',
                'COLOR' => 'BLACK',
                'CODE' => '4688B',
              ],
              105 => [
                'BRAND' => 'XLEON',
                'SIZE' => '30',
                'COLOR' => 'ASH',
                'CODE' => 'B-2043',
              ],
              106 => [
                'BRAND' => 'XLEON',
                'SIZE' => '31',
                'COLOR' => 'ASH',
                'CODE' => 'B-2043',
              ],
              107 => [
                'BRAND' => 'XLEON',
                'SIZE' => '32',
                'COLOR' => 'ASH',
                'CODE' => 'B-2043',
              ],
              108 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'ASH',
                'CODE' => 'B-2043',
              ],
              109 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'ASH',
                'CODE' => 'B-2043',
              ],
              110 => [
                'BRAND' => 'XLEON',
                'SIZE' => '34',
                'COLOR' => 'ASH',
                'CODE' => 'B-2043',
              ],
              111 => [
                'BRAND' => 'XLEON',
                'SIZE' => '38',
                'COLOR' => 'ASH',
                'CODE' => 'B-2043',
              ],
              112 => [
                'BRAND' => 'XLEON',
                'SIZE' => '40',
                'COLOR' => 'ASH',
                'CODE' => 'B-2043',
              ],
              113 => [
                'BRAND' => 'XLEON',
                'SIZE' => '30',
                'COLOR' => 'ASH',
                'CODE' => 'B-2043',
              ],
              114 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'W3523',
              ],
              115 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'W3523',
              ],
              116 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'W3523',
              ],
              117 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'W3523',
              ],
              118 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'W3523',
              ],
              119 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '50',
                'COLOR' => 'BLACK',
                'PRICE' => '150',
                'CODE' => 'AS201804',
              ],
              120 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '44',
                'COLOR' => 'BLACK',
                'PRICE' => '150',
                'CODE' => 'AS201804',
              ],
              121 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '150',
                'CODE' => 'AS201804',
              ],
              122 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '50',
                'COLOR' => 'BLACK',
                'PRICE' => '150',
                'CODE' => 'AS201804',
              ],
              123 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '42',
                'COLOR' => 'BLACK',
                'PRICE' => '150',
                'CODE' => '3006',
              ],
              124 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'PRICE' => '150',
                'CODE' => '3006',
              ],
              125 => [
                'BRAND' => 'MONAR',
                'SIZE' => '36',
                'COLOR' => 'BLACK',
                'CODE' => 'MYS418',
              ],
              126 => [
                'BRAND' => 'MONAR',
                'SIZE' => '31',
                'COLOR' => 'BLACK',
                'CODE' => 'MYS418',
              ],
              127 => [
                'BRAND' => 'MONAR',
                'SIZE' => '40',
                'COLOR' => 'BLACK',
                'CODE' => 'MYS418',
              ],
              128 => [
                'BRAND' => 'MONAR',
                'SIZE' => '33',
                'COLOR' => 'BLACK',
                'CODE' => 'MYS418',
              ],
              129 => [
                'BRAND' => 'GIORGIO ARMANI',
                'SIZE' => '40',
                'COLOR' => 'BROWN',
                'CODE' => '100404099',
              ],
              130 => [
                'BRAND' => 'GIORGIO ARMANI',
                'SIZE' => '42',
                'COLOR' => 'BROWN',
                'CODE' => '100404099',
              ],
              131 => [
                'BRAND' => 'MONAR',
                'SIZE' => '31',
                'COLOR' => 'KAKI',
                'CODE' => 'MSY418',
              ],
              132 => [
                'BRAND' => 'MONAR',
                'SIZE' => '32',
                'COLOR' => 'BLACK',
                'CODE' => 'MYS309',
              ],
              133 => [
                'BRAND' => 'MONAR',
                'SIZE' => '32',
                'COLOR' => 'BLACK',
                'CODE' => 'MYS418',
              ],
              134 => [
                'BRAND' => 'MONAR',
                'SIZE' => '31',
                'COLOR' => 'BROWN',
                'CODE' => 'MS18',
              ],
              135 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '52',
                'COLOR' => 'NAVY BLUE',
                'PRICE' => '250',
                'CODE' => 'BLN08',
              ],
              136 => [
                'BRAND' => 'MONAR',
                'SIZE' => '33',
                'COLOR' => 'BLACK',
                'CODE' => 'MYS418',
              ],
              137 => [
                'BRAND' => 'BCSS',
                'SIZE' => '40',
                'COLOR' => 'KAKI',
                'CODE' => '100404099',
              ],
              138 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '46',
                'COLOR' => 'KAKI',
                'PRICE' => '200',
                'CODE' => 'BLN03',
              ],
              139 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '46',
                'COLOR' => 'KAKI',
                'PRICE' => '200',
                'CODE' => 'BLN03',
              ],
              140 => [
                'BRAND' => 'XLEON',
                'SIZE' => '30',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'B2043',
              ],
              141 => [
                'BRAND' => 'XLEON',
                'SIZE' => '31',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'B2043',
              ],
              142 => [
                'BRAND' => 'XLEON',
                'SIZE' => '32',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'B2043',
              ],
              143 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'B2043',
              ],
              144 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'B2043',
              ],
              145 => [
                'BRAND' => 'XLEON',
                'SIZE' => '34',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'B2043',
              ],
              146 => [
                'BRAND' => 'XLEON',
                'SIZE' => '36',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'B2043',
              ],
              147 => [
                'BRAND' => 'XLEON',
                'SIZE' => '38',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'B2043',
              ],
              148 => [
                'BRAND' => 'XLEON',
                'SIZE' => '40',
                'COLOR' => 'BLUE BLACK',
                'CODE' => 'B2043',
              ],
              149 => [
                'BRAND' => 'MONAR',
                'SIZE' => '30',
                'COLOR' => 'KAKI',
                'PRICE' => '200',
                'CODE' => 'MYS309',
              ],
              150 => [
                'BRAND' => 'MONAR',
                'SIZE' => '36',
                'COLOR' => 'KAKI',
                'PRICE' => '200',
                'CODE' => 'MYS418',
              ],
              151 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '46',
                'COLOR' => 'KAKI',
                'PRICE' => '200',
                'CODE' => 'MAS-55',
              ],
              152 => [
                'BRAND' => 'MONAR',
                'SIZE' => '54',
                'COLOR' => 'BLACK',
                'CODE' => 'MYR408',
              ],
              153 => [
                'BRAND' => 'MONAR',
                'SIZE' => '58',
                'COLOR' => 'BLACK',
                'CODE' => 'MYR408',
              ],
              154 => [
                'BRAND' => 'MONAR',
                'SIZE' => '58',
                'COLOR' => 'BLACK',
                'CODE' => 'MYR408',
              ],
              155 => [
                'BRAND' => 'MONAR',
                'SIZE' => '52',
                'COLOR' => 'BLACK',
                'CODE' => 'MYR408',
              ],
              156 => [
                'BRAND' => 'MONAR',
                'SIZE' => '60',
                'COLOR' => 'BLACK',
                'CODE' => 'MYR408',
              ],
              157 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '48',
                'COLOR' => 'GRAY',
                'CODE' => '3006',
              ],
              158 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '50',
                'COLOR' => 'GRAY',
                'CODE' => '3006',
              ],
              159 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '48',
                'COLOR' => 'GRAY',
                'CODE' => '3006',
              ],
              160 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '48',
                'COLOR' => 'GRAY',
                'CODE' => '3006',
              ],
              161 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '48',
                'COLOR' => 'GRAY',
                'CODE' => '3006',
              ],
              162 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '48',
                'COLOR' => 'GRAY',
                'CODE' => '3006',
              ],
              163 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '50',
                'COLOR' => 'GRAY',
                'CODE' => '3006',
              ],
              164 => [
                'BRAND' => 'MONAR',
                'SIZE' => '40',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYS418',
              ],
              165 => [
                'BRAND' => 'MONAR',
                'SIZE' => '33',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYS418',
              ],
              166 => [
                'BRAND' => 'MONAR',
                'SIZE' => '36',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYS418',
              ],
              167 => [
                'BRAND' => 'MONAR',
                'SIZE' => '36',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYS418',
              ],
              168 => [
                'BRAND' => 'MONAR',
                'SIZE' => '31',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYS418',
              ],
              169 => [
                'BRAND' => 'MONAR',
                'SIZE' => '33',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYS418',
              ],
              170 => [
                'BRAND' => 'MONAR',
                'SIZE' => '32',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYS418',
              ],
              171 => [
                'BRAND' => 'XLEON',
                'SIZE' => '34',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2002094',
              ],
              172 => [
                'BRAND' => 'XLEON',
                'SIZE' => '30',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2002094',
              ],
              173 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2002094',
              ],
              174 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2002094',
              ],
              175 => [
                'BRAND' => 'XLEON',
                'SIZE' => '36',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2002094',
              ],
              176 => [
                'BRAND' => 'XLEON',
                'SIZE' => '38',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2002094',
              ],
              177 => [
                'BRAND' => 'XLEON',
                'SIZE' => '40',
                'COLOR' => 'BLUE BLACK',
                'CODE' => '2002094',
              ],
              178 => [
                'BRAND' => 'PIERRE CARLOS',
                'SIZE' => '42',
                'COLOR' => 'KAKI',
                'CODE' => '018-6',
              ],
              179 => [
                'BRAND' => 'PIERRE CARLOS',
                'SIZE' => '46',
                'COLOR' => 'KAKI',
                'CODE' => '018-6',
              ],
              180 => [
                'BRAND' => 'PIERRE CARLOS',
                'SIZE' => '50',
                'COLOR' => 'KAKI',
                'CODE' => '018-6',
              ],
              181 => [
                'BRAND' => 'PIERRE CARLOS',
                'SIZE' => '44',
                'COLOR' => 'KAKI',
                'CODE' => '018-6',
              ],
              182 => [
                'BRAND' => 'MONAR',
                'SIZE' => '56',
                'COLOR' => 'BLACK',
                'CODE' => 'MYR408',
              ],
              183 => [
                'BRAND' => 'MONAR',
                'SIZE' => '52',
                'COLOR' => 'BLACK',
                'CODE' => 'MYR408',
              ],
              184 => [
                'BRAND' => 'MONAR',
                'SIZE' => '56',
                'COLOR' => 'BLACK',
                'CODE' => 'MYR408',
              ],
              185 => [
                'BRAND' => 'MONAR',
                'SIZE' => '54',
                'COLOR' => 'BLACK',
                'CODE' => 'MYR408',
              ],
              186 => [
                'BRAND' => 'BERENDI',
                'SIZE' => '46',
                'COLOR' => 'BROWN',
                'CODE' => '23151309058',
              ],
              187 => [
                'BRAND' => 'GEORGE',
                'COLOR' => 'BLACK',
                'CODE' => '23151309058',
              ],
              188 => [
                'BRAND' => 'LWD',
                'SIZE' => '29',
                'COLOR' => 'LIGHT BLUE',
                'CODE' => '23151309058',
              ],
              189 => [
                'BRAND' => 'GIORGIO ARMANI',
                'COLOR' => 'BROWN',
                'CODE' => '23151309058',
              ],
              190 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '44',
                'COLOR' => 'BLACK',
                'CODE' => 'MASG05',
              ],
              191 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '48',
                'COLOR' => 'BLACK',
                'CODE' => 'MASG05',
              ],
              192 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '40',
                'COLOR' => 'BLACK',
                'CODE' => 'MASG05',
              ],
              193 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '50',
                'COLOR' => 'BLACK',
                'CODE' => 'MASG05',
              ],
              194 => [
                'BRAND' => 'BALLIANI',
                'SIZE' => '50',
                'COLOR' => 'NAVY BLUE',
                'CODE' => 'BLN08',
              ],
              195 => [
                'BRAND' => 'MONAR',
                'SIZE' => '52',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYR408',
              ],
              196 => [
                'BRAND' => 'MONAR',
                'SIZE' => '52',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYR408',
              ],
              197 => [
                'BRAND' => 'MONAR',
                'SIZE' => '58',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYR408',
              ],
              198 => [
                'BRAND' => 'MONAR',
                'SIZE' => '58',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYR408',
              ],
              199 => [
                'BRAND' => 'MONAR',
                'SIZE' => '54',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYR408',
              ],
              200 => [
                'BRAND' => 'MONAR',
                'SIZE' => '58',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYR408',
              ],
              201 => [
                'BRAND' => 'MONAR',
                'SIZE' => '56',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYR408',
              ],
              202 => [
                'BRAND' => 'MONAR',
                'SIZE' => '54',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYR408',
              ],
              203 => [
                'BRAND' => 'MONAR',
                'SIZE' => '56',
                'COLOR' => 'BLUE BLACK',
                'PRICE' => '200',
                'CODE' => 'MYR408',
              ],
              204 => [
                'BRAND' => 'MONAR',
                'SIZE' => '48',
                'COLOR' => 'ASH',
                'CODE' => 'WR505',
              ],
              205 => [
                'BRAND' => 'MONAR',
                'SIZE' => '50',
                'COLOR' => 'ASH',
                'CODE' => 'WR505',
              ],
              206 => [
                'BRAND' => 'MONAR',
                'SIZE' => '52',
                'COLOR' => 'ASH',
                'CODE' => 'WR505',
              ],
              207 => [
                'BRAND' => 'MONAR',
                'SIZE' => '54',
                'COLOR' => 'ASH',
                'CODE' => 'WR505',
              ],
              208 => [
                'BRAND' => 'MONAR',
                'SIZE' => '48',
                'COLOR' => 'ASH',
                'CODE' => 'WR505',
              ],
              209 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'ASH',
                'CODE' => 'WR505',
              ],
              210 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'ASH',
                'CODE' => 'WR505',
              ],
              211 => [
                'BRAND' => 'MONAR',
                'SIZE' => '44',
                'COLOR' => 'ASH',
                'CODE' => 'WR505',
              ],
              212 => [
                'BRAND' => 'MONAR',
                'SIZE' => '44',
                'COLOR' => 'ASH',
                'CODE' => 'WR505',
              ],
              213 => [
                'BRAND' => 'MONAR',
                'SIZE' => '42',
                'COLOR' => 'ASH',
                'CODE' => 'WR505',
              ],
              214 => [
                'BRAND' => 'MONAR',
                'SIZE' => '48',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              215 => [
                'BRAND' => 'MONAR',
                'SIZE' => '50',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              216 => [
                'BRAND' => 'MONAR',
                'SIZE' => '44',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              217 => [
                'BRAND' => 'MONAR',
                'SIZE' => '42',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              218 => [
                'BRAND' => 'MONAR',
                'SIZE' => '46',
                'COLOR' => 'BLACK',
                'CODE' => 'WR523',
              ],
              219 => [
                'BRAND' => 'XLEON',
                'SIZE' => '30',
                'COLOR' => 'BLACK',
                'CODE' => '2131',
              ],
              220 => [
                'BRAND' => 'XLEON',
                'SIZE' => '32',
                'COLOR' => 'BLACK',
                'CODE' => '2131',
              ],
              221 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'BLACK',
                'CODE' => '2131',
              ],
              222 => [
                'BRAND' => 'XLEON',
                'SIZE' => '33',
                'COLOR' => 'BLACK',
                'CODE' => '2131',
              ],
              223 => [
                'BRAND' => 'XLEON',
                'SIZE' => '34',
                'COLOR' => 'BLACK',
                'CODE' => '2131',
              ],
              224 => [
                'BRAND' => 'XLEON',
                'SIZE' => '34',
                'COLOR' => 'BLACK',
                'CODE' => '2131',
              ],
              225 => [
                'BRAND' => 'XLEON',
                'SIZE' => '36',
                'COLOR' => 'BLACK',
                'CODE' => '2131',
              ],
              226 => [
                'BRAND' => 'XLEON',
                'SIZE' => '38',
                'COLOR' => 'BLACK',
                'CODE' => '2131',
              ],
              227 => [
                'BRAND' => 'XLEON',
                'SIZE' => '40',
                'COLOR' => 'BLACK',
                'CODE' => '2131',
              ],
              228 => [
                'BRAND' => 'MONAR',
                'SIZE' => '48',
                'COLOR' => 'DARK BROWN',
                'CODE' => 'WR505',
              ],
              229 => [
                'BRAND' => 'MONAR',
                'SIZE' => '52',
                'COLOR' => 'DARK BROWN',
                'CODE' => 'WR505',
              ],
              230 => [
                'BRAND' => 'MONAR',
                'SIZE' => '48',
                'COLOR' => 'DARK BROWN',
                'CODE' => 'WR505',
              ],
              231 => [
                'BRAND' => 'MONAR',
                'SIZE' => '50',
                'COLOR' => 'DARK BROWN',
                'CODE' => 'WR505',
              ],
              232 => [
                'BRAND' => 'MONAR',
                'SIZE' => '36',
                'COLOR' => 'BLACK',
                'CODE' => 'MYS309',
              ],
              233 => [
                'BRAND' => 'MONAR',
                'SIZE' => '31',
                'COLOR' => 'BLACK',
                'CODE' => 'MYS309',
              ],
              234 => [
                'BRAND' => 'MONAR',
                'SIZE' => '33',
                'COLOR' => 'BROWN',
                'CODE' => 'MYS418',
              ],
              235 => [
                'BRAND' => 'MONAR',
                'SIZE' => '32',
                'COLOR' => 'BROWN',
                'CODE' => 'MYS418',
              ],
              236 => [
                'BRAND' => 'MONAR',
                'SIZE' => '33',
                'COLOR' => 'BROWN',
                'CODE' => 'MYS418',
              ],
              237 => [
                'BRAND' => 'MONAR',
                'SIZE' => '40',
                'COLOR' => 'BROWN',
                'CODE' => 'MYS418',
              ],
            ],
            'SHORTS' => [
              0 => [
                'BRAND' => 'PULO SMLCH',
                'SIZE' => '40',
                'COLOR' => 'LIGHT GRAY',
                'PRICE' => '100',
                'CODE' => 'P2021-27#',
              ],
              1 => [
                'BRAND' => 'PULO SMLCH',
                'SIZE' => '38',
                'COLOR' => 'LIGHT GRAY',
                'PRICE' => '100',
                'CODE' => 'P2021-27#',
              ],
              2 => [
                'BRAND' => 'PULO SMLCH',
                'SIZE' => '34',
                'COLOR' => 'LIGHT GRAY',
                'PRICE' => '100',
                'CODE' => 'P2021-27#',
              ],
              3 => [
                'BRAND' => 'PULO SMLCH',
                'SIZE' => '38',
                'COLOR' => 'LIGHT GRAY',
                'PRICE' => '100',
                'CODE' => 'P2021-27#',
              ],
              4 => [
                'BRAND' => 'PULO SMLCH',
                'SIZE' => '34',
                'COLOR' => 'BLACK',
                'PRICE' => '100',
                'CODE' => 'P2021-19#',
              ],
              5 => [
                'BRAND' => 'PULO SMLCH',
                'SIZE' => '38',
                'COLOR' => 'BLACK',
                'PRICE' => '100',
                'CODE' => 'P2021-19#',
              ],
              6 => [
                'BRAND' => 'PULO SMLCH',
                'SIZE' => '38',
                'COLOR' => 'BLACK',
                'PRICE' => '100',
                'CODE' => 'P2021-19#',
              ],
              7 => [
                'BRAND' => 'PULO SMLCH',
                'SIZE' => '36',
                'COLOR' => 'BLACK',
                'PRICE' => '100',
                'CODE' => 'P2021-19#',
              ],
              8 => [
                'BRAND' => 'PULO SMLCH',
                'SIZE' => '36',
                'COLOR' => 'KAKI',
                'PRICE' => '100',
                'CODE' => 'P2021-22#',
              ],
              9 => [
                'BRAND' => 'PULO SMLCH',
                'SIZE' => '40',
                'COLOR' => 'KAKI',
                'PRICE' => '100',
                'CODE' => 'P2021-22#',
              ],
              10 => [
                'BRAND' => 'PULO SMLCH',
                'SIZE' => '40',
                'COLOR' => 'KAKI',
                'PRICE' => '100',
                'CODE' => 'P2021-22#',
              ],
              11 => [
                'BRAND' => 'CALVIN KLEIN',
                'SIZE' => '33',
                'PRICE' => '80',
                'CODE' => '36182685841',
              ],
              12 => [
                'BRAND' => 'CALVIN KLEIN',
                'SIZE' => '34',
                'PRICE' => '80',
                'CODE' => '36182685841',
              ],
            ],
        ];


        foreach ($products as $category => $items) {

            foreach ($items as $item) {
              $record['track_id'] = null;
              $record['name'] = null;
              $record['code'] = null;
              $record['barcode'] = null;
              $record['size_type'] = null;
              $record['stock'] = null;
              $record['color'] = null;
              $record['price'] = null;
              $record['description'] = null;
              // track id
              if (isset($item['TRACKER ID'])) {
                $record['track_id'] = $item['TRACKER ID'];
              }
              // brand
              if (isset($item['BRAND'])) {
                $record['name'] = $item['BRAND'];
              }
              // code
              if (isset($item['CODE'])) {
                $record['code'] = $item['CODE'];
                $record['barcode'] = $item['CODE'];
              }
              // size
              if (isset($item['SIZE'])) {
                $record['size_type'] = $item['SIZE'];
              }
              // color
              if (isset($item['COLOR'])) {
                $record['color'] = $item['COLOR'];
              }
              // price
              if (isset($item['PRICE'])) {
                $record['price'] = $item['PRICE'];
              }
              // stock
              if (isset($item['QTY'])) {
                $record['stock'] = $item['QTY'];
              }
              // description
              if (isset($item['DESCRIPTION'])) {
                $record['description'] = $item['DESCRIPTION'];
              }
              // category
              $record['category'] = $category;
      
              \App\Models\Product::factory()->create($record);
            }
          }
    }
}
